version: '2.1'
services:
  container_nanite:
    image: my/container_nanite
    container_name: container_nanite
    ports:
      - "20102:20102"
      - "21102:21102"
    volumes:
    - ./conf/Nanite.conf:/root/.Nanite/Nanite.conf
